function  AmtB_GlnKfree = calcAmtB_GlnKfree(GlnK_OGfree, AmtBtotal, Kglnkamtb)

AmtB_GlnKfree = 0.5*( - GlnK_OGfree + AmtBtotal - Kglnkamtb ...
	+ RPowerR( (GlnK_OGfree - AmtBtotal + Kglnkamtb)*(GlnK_OGfree - AmtBtotal + Kglnkamtb) ...
	+ 4*Kglnkamtb*AmtBtotal, 0.5 ) );
